### ISSUE TITLE
undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by lunochod** [clMathLibraries/clBLAS#101]
clBLAS fails to link in master and develop branch. I opened a pull request that was closed. The fix can be found here:

https://github.com/lunochod/clBLAS/blob/master/src/tests/CMakeLists.txt

**Comment by pavanky** [comment]
I don't see a PR from you regarding this ?

**Comment by lunochod** [comment]
https://github.com/clMathLibraries/clBLAS/pull/102

**Comment by TimmyLiu** [comment]
I merged the pull request. Can you close the issue?
