### ISSUE TITLE
Getting the generated kernels

### ISSUE THREAD

**Issue by blueberry** [clMathLibraries/clBLAS#104]
Is there a way to see how a generated kernel for a certain blas operation looks like? I am looking at how to use  clBLAS kernels in another library, but can not follow the generation process in clBLAS. Is there something like "dump the generated kernels to a string"?

**Comment by CNugteren** [comment]
One option would be to simply `printf` the kernels yourself by modifying the source. I did that myself a while back, and, if I recall it correctly, it can be done like this (example for GEMM):

- Open `src/library/blas/gens/gemm.c`
- Add `printf(“%s”, ctx);` just before the return of the `blockGen` function

**Comment by gregsomers** [comment]
Compile clBLAS from source. You need the cmake variable BLAS_DUMP_CLBLAS_KERNELS set to ON. You can do the interactive config cmake -i, it will prompt to enter a value.

After linking with the newly compiled lib, it will dump all of the kernels to the directory the program was executed from. It should dump the kernel for every single clBLAS call.

**Comment by blueberry** [comment]
Thank you, Greg.

**Comment by TimmyLiu** [comment]
Can we close this issue?
