### ISSUE TITLE
Disabling 'build client' in develop build causes build to fail

### ISSUE THREAD

**Issue by hughperkins** [clMathLibraries/clBLAS#114]
to replicate:
- clone develop branch, on ubuntu 14.04 64-bit
- run ccmake
- disable everything except shared library and print malloc errors
- press 'c' and 'g' to generate
=> error about tyring to install non-existent target `Library`

**Comment by TimmyLiu** [comment]
I believe you would also need to click BUILD_RUNTIME. 
BUILD_SHARED_LIBS was introduced in PR #67 to allow users build static libraries.

**Comment by hughperkins** [comment]
Ok, I see.
