### ISSUE TITLE
build of development version on NVIDIA platform fails

### ISSUE THREAD

**Issue by lunochod** [clMathLibraries/clBLAS#117]
clEnqueueFillBuffer() used by clBLAS requires OpenCL 1.2. The NV driver and OpenCL runtime have recently been updated to support OpenCL 1.2, but CUDA-7.0 still ships with the OpenCL 1.1 header files. To build with NV OpenCL, download OpenCL header files from khronos here:

https://www.khronos.org/registry/cl/api/1.2/

and place in /usr/local/cuda-7.0/include/CL/

**Comment by TimmyLiu** [comment]
Thanks for pointing this out and provide a solution. I had to do something like this to get travis CI working.

**Comment by TimmyLiu** [comment]
sounds like (issue #176 ) cuda 7.5 fixed this issue.
