### ISSUE TITLE
Please tag the new upstream release

### ISSUE THREAD

**Issue by ghisvail** [clMathLibraries/clBLAS#121]
I noticed that the version number in ```master``` was bumped to 2.6 after a recent merge from ```develop```. I am guessing this means a new upstream release has been made. Could you guys please push a tag for it ?

Many thanks.

**Comment by TimmyLiu** [comment]
Hi,

We were kinda waiting for 14.502 linux driver to make the release. We have made a new release now.

Thanks for your patience!

**Comment by TimmyLiu** [comment]
Can we close this issue now that releases have been made?

**Comment by ghisvail** [comment]
Please go ahead.
