### ISSUE TITLE
Compiled libraries for Mac

### ISSUE THREAD

**Issue by wanderine** [clMathLibraries/clBLAS#123]
It would be nice if you can provide compiled libraries for the Mac platform.

**Comment by zachmayer** [comment]
Or at least up-to-date docs for compiling on a mac.  I'd be happy to submit a formula to https://github.com/Homebrew/homebrew if I could get a little help creating it.  (Homebrew already provides a [formula for boost](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb))
It'd be really cool to be able to:
```{R}
brew install boost
brew install clblas
```

**Comment by zachmayer** [comment]
For example, we can currently instal openblas on a mac via:
```{bash}
brew tap homebrew/science
brew install openblas
```

**Comment by tdsmith** [comment]
A clblas formula exists in homebrew/science: https://github.com/Homebrew/homebrew-science/commits/master/clblas.rb

`brew install homebrew/science/clblas`

**Comment by ddofer** [comment]
It would be a good idea to put this in the README/instructions!

(I just spent a while digging through issues and files trying to figure out how to install/run/compile. This sidesteps all that)
