### ISSUE TITLE
Add support of open source blas for tests

### ISSUE THREAD

**Issue by inferrna** [clMathLibraries/clBLAS#155]
ACML is closed source and EOL, why not to add support of any other BLAS implementation? For example, someone may want to build and test clBLAS on ARM or MIPS platform.

**Comment by TimmyLiu** [comment]
You can do this by unclicking "CORR_TEST_WITH_ACML" and the test suite will try link against netlib blas.

**Comment by inferrna** [comment]
Done, but it can't find netlib path itself. In Ubuntu it is /usr/lib/libblas/libblas.so.3 - please add it to FindNetlib.cmake

**Comment by TimmyLiu** [comment]
Hi with PR #181 on my Ubuntu system I can find and build test with libblas.so fairly straightforward. Can you verify that it works for you?

**Comment by hughperkins** [comment]
Seems like this is a. plausibly fixed in 'develop' b. really old, and probably can be closed?
