### ISSUE TITLE
Fatal error, OpenCL or clblas initialization failed! Leaving the test.

### ISSUE THREAD

**Issue by inferrna** [clMathLibraries/clBLAS#156]
Trying to repeat https://gist.github.com/inferrna/5e3fd6ec9d9c990a3256 with CPU I got another error
```
$ staging/test-short --gtest_filter=RowMajor_SmallRange/GEMM.sgemm/0
Initialize OpenCL and clblas...
/home/inferno/.dev/OpenCL/clBLAS/src/tests/BlasBase.cpp:217: Failure
Value of: clGetDeviceIDs(platform_, devType_, 1, &primaryDevice_, __null)
  Actual: -1
Expected: 0
Fatal error, OpenCL or clblas initialization failed! Leaving the test.
```
But actually I have 2 CPU-only implementation of OpenCL
My clinfo:
https://gist.github.com/inferrna/5e3fd6ec9d9c990a3256

**Comment by anadon** [comment]
2 CPU implementations of OpenCL?  Could you clarify your setup?  It sounds unusual.

**Comment by hughperkins** [comment]
Seems like this is really old and could be closed?
