### ISSUE TITLE
Tests fail to build in China

### ISSUE THREAD

**Issue by hughperkins** [clMathLibraries/clBLAS#182]
Hi,

gtest download is unavailable from China, specifically this url: URL http://googletest.googlecode.com/files/gtest-1.7.0.zip

Plesae can you:
- either add gtest directly to the repo (it's only 1MB or so; tiny), or else
- update to use the https://github.com/google/googletest/archive/release-1.7.0.zip link, which is available

(Current output from build:

```
CMake Error at gtest-external-stamp/download-gtest-external.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/user/git/clBLAS/src/build/tests/gtest-external-prefix/src/gtest-1.7.0.zip]
      expected hash: [2d6ec8ccdf5c46b05ba54a9fd1d130d7]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
```
)

(Edit: note: I will send a pull request for this, so it's just for info really)

**Comment by sivagnanamn** [comment]
Unavailable from Japan too.
