### ISSUE TITLE
xgemm compilation error

### ISSUE THREAD

**Issue by MajorBreakfast** [clMathLibraries/clBLAS#195]
I get the following on a non-AMD card:

```
<kernel>:1:369: error: array initializer must be an initializer list
```

sgemm_Col_NT_B1_MX032_NX032_KX16_SINGLE_src.cpp and many others contain:
```OpenCL
float rC[2][2] = { (float)0 };
```

To fix it:
```OpenCL
float rC[2][2] = {{ (float)0 }};
```

Same goes for the double versions.

**Comment by pavanky** [comment]
@MajorBreakfast This is a problem in `master`, but it's been resovled in `develop` as far as I can tell. Can you verify this ? If so we can close the issue.

**Comment by MajorBreakfast** [comment]
I peeked at the code and this seems to be the case. I'll reopen if I've any further problems with this. Thx!
