### ISSUE TITLE
cmake needs to detect python and python version

### ISSUE THREAD

**Issue by TimmyLiu** [clMathLibraries/clBLAS#196]
since python 2.7 is required now, cmake should detect python as well as python version at config time. 
We can probably use FindPythonLibs here: https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html

**Comment by pavanky** [comment]
:+1: I have been forcing cmake to use `python2` manually.

**Comment by pavanky** [comment]
@TimmyLiu, I sent a patch in #199 that should work with both python2 and python3 interpreters.

**Comment by TimmyLiu** [comment]
@pavanky thanks for fixing for python3. But I still think cmake should at least check for python and complains if the system does not have python.

**Comment by pavanky** [comment]
@TimmyLiu you should be using [FindPythonInterp](https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html) instead. `FindPythonLibs` is required when you are compiling python modules I think.

**Comment by pavanky** [comment]
Alright sent a new PR for fixing this.
