### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ashbachj** [clMathLibraries/clBLAS#20]
Hi, I am attempting to run some examples and the tests before I incorporate clBLAS into my project. Pretty much everything I run results in the following error

AN INTERNAL KERNEL BUILD ERROR OCCURRED!
device name = Quadro FX 5800
error = -11
memory pattern = Cached global memory based block gemm, computing kernel generator
Subproblem dimensions: dims[0].itemY = 64, dims[0].itemX = 32, dims[0].y = 64, dims[0].x = 32, dims[0].bwidth = 4; ; dims[1].itemY = 8, dims[1].itemX = 4, dims[1].y = 8, dims[1].x = 4, dims[1].bwidth = 4; ; 
Parallelism granularity: pgran->wgDim = 2, pgran->wgSize[0] = 8, pgran->wgSize[1] = 8, pgran->wfSize = 64
Kernel extra flags: 939554576
Source:
_source dump cut_

Build log:

Error in processing command line: Don't understand command line argument "-g"!

Would you be able to assist me with this problem?
Thanks

**Comment by jonathantompson** [comment]
I also wanted to confirm that this was also a problem (using OpenCL.lib from NVidia's CUDA 6.5 SDK).  Commenting out the -g flag line also worked for me.
