### ISSUE TITLE
AutoGemm kernels sometimes produce nans when beta is 0, C is not initialized

### ISSUE THREAD

**Issue by pavanky** [clMathLibraries/clBLAS#201]
The code to reproduce the problem can be seen here:

https://gist.github.com/shehzan10/df2a318d309776a2200d

**Comment by TimmyLiu** [comment]
@pavanky Is this a cgemm only issue? When merging PR #199 I built the code with python 2.7 on hawaii and fiji on both windows and linux and did not see any test fails.

**Comment by pavanky** [comment]
@TimmyLiu This is only a problem with cgemm and zgemm.

**Comment by TimmyLiu** [comment]
@pavanky can we close this issue with pr #202  being merged?

**Comment by pavanky** [comment]
Oops, I thought it'd be closed automatically.
