### ISSUE TITLE
cl_ext.h and OpenCL-caffe

### ISSUE THREAD

**Issue by sliterok** [clMathLibraries/clBLAS#204]
Log:
mint@mintpc ~/3/OpenCL-caffe/build $ sudo make
[  1%] Built target proto
[  1%] Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
In file included from /home/mint/3/OpenCL-caffe/include/caffe/blob.hpp:8:0,
                 from /home/mint/3/OpenCL-caffe/src/caffe/blob.cpp:4:
/home/mint/3/OpenCL-caffe/include/caffe/common.hpp:22:23: fatal error: CL/cl_ext.h: No such file or directory
 #include <CL/cl_ext.h>
                       ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/blob.cpp.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by pavanky** [comment]
@sliterok The build log you posted does not seem to indicate it has anything to do with clBLAS. Are you missing some information?

**Comment by sliterok** [comment]
I can make full reproduction of problem if you need
Wait a bit.

**Comment by sliterok** [comment]
>mkdir clcaffe

>cd clcaffe

>sudo git clone https://github.com/amd/OpenCL-caffe

>mkdir build

>cd build

>Downloading extracting compiled clblas to ~/clcaffe/OpenCL-caffe/build/clBLAS-2.8.0
>sudo cmake -DBLAS=open -DUSE_OPENCL=ON -DUSE_CLGEMM=ON -DCMAKE_BUILD_TYPE=Release -DUSE_TIMER=OFF -DCMAKE_INSTALL_PREFIX=release -DOPENCL_INCLUDE_DIRS=/opt/AMDAPPSDK-3.0-0/include -DOPENCL_LIBRARIES=/opt/AMDAPPSDK-3.0-0/lib/x86_64/libOpenCL.so -DCLBLAS_INCLUDE_DIRS=/home/mint/clcaffe/OpenCL-caffe/build/clBLAS-2.8.0/include -DCLBLAS_LIBRARIES=/home/mint/clcaffe/OpenCL-caffe/build/clBLAS-2.8.0/lib64/libclBLAS.so ..
Log: http://pastebin.com/60hJiM4e

>sudo make
[  0%] Running C++/Python protocol buffer compiler on /home/mint/clcaffe/OpenCL-caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
Scanning dependencies of target caffe
[  1%] Building CXX object src/caffe/CMakeFiles/caffe.dir/blob.cpp.o
In file included from /home/mint/clcaffe/OpenCL-caffe/include/caffe/common.hpp:20:0,
                 from /home/mint/clcaffe/OpenCL-caffe/include/caffe/blob.hpp:8,
                 from /home/mint/clcaffe/OpenCL-caffe/src/caffe/blob.cpp:4:
/home/mint/clcaffe/OpenCL-caffe/build/clBLAS-2.8.0/include/clBLAS.h:35:19: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
                   ^
compilation terminated.
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/blob.cpp.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by sliterok** [comment]
Fixed with installing OpenGL
