### ISSUE TITLE
Use consistent format for tags

### ISSUE THREAD

**Issue by ghisvail** [clMathLibraries/clBLAS#217]
The recent release of clBLAS version `2.10` was tagged as `2.10` not `v2.10` as used previously with `v2.8`, `v2.6`, etc. Please consider using consistent tag formats, as it requires the configuration of the downstream packaging tools to be changed each time. Thanks.

**Comment by TimmyLiu** [comment]
thanks for the catch! I edited the release hopefully it is okay.

**Comment by TimmyLiu** [comment]
Hi, can we close this issue?

**Comment by ghisvail** [comment]
sure, closing now.
