### ISSUE TITLE
Any successful builds with OSX 10.11?

### ISSUE THREAD

**Issue by gaming-hacker** [clMathLibraries/clBLAS#225]
all i see are problems, i just tried and build fails miserably, can't find system SDK or libs.  

another reason why i can't stand cmake.  just give me a  Makefile.

**Comment by pavanky** [comment]
You can install from homebrew. It's part of [homebrew science](https://github.com/Homebrew/homebrew-science/blob/master/clblas.rb).

**Comment by gaming-hacker** [comment]
i'm not a huge fan of homebrew.  i'm trying to build openBlas and compare to clBlas.

**Comment by pavanky** [comment]
@gaming-hacker did you try building the develop branch though ? A few issues related to clang were fixed in it.
