### ISSUE TITLE
`make clean` deletes UserGemmClKernels.cc causing subsequent build to fail

### ISSUE THREAD

**Issue by matejaputic** [clMathLibraries/clBLAS#231]
As it says in the slug, running `make clean` from the build directory deletes `src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmClKernels.cc`. 

To recreate the problem:
```
> git clone https://github.com/clMathLibraries/clBLAS.git && cd clBLAS
> mkdir build && cd build
> cmake ../src
> make
...
> make clean && make
```

A workaround is to run:
```
> git checkout src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmClKernels.cc
```

then try the build again.

**Comment by pavanky** [comment]
I think this is fixed in devleop branch. Are you using the master branch ?

**Comment by matejaputic** [comment]
Yes, I am on the master branch

**Comment by tingxingdong** [comment]
u updated to the latest one ? master branch should fix it, too.


On Wed, Feb 24, 2016 at 5:52 PM, Mateja Putic <notifications@github.com>
wrote:

> Yes, I am on the master branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clMathLibraries/clBLAS/issues/231#issuecomment-188523923>
> .
>



-- 
Tingxing dong

**Comment by matejaputic** [comment]
Yes, I just did fresh clone and it still exhibits the same behavior

**Comment by pavanky** [comment]
@tingxingdong The [fix](https://www.youtube.com/watch?v=eFqj-jgA6Mg&feature=youtu.be&t=8m56s) was on Jan 6th. The head on master is from Jan 5th. It hasn't been pushed to master yet.

@matejaputic can you test on the `develop` branch ?. We can close this issue if it's been fixed.

**Comment by matejaputic** [comment]
Looks like it's been fixed on the develop branch, thanks
