### ISSUE TITLE
CL_INVALID_BUILD_OPTIONS (-43) when running tests on mesa

### ISSUE THREAD

**Issue by anadon** [clMathLibraries/clBLAS#240]
https://gist.github.com/anadon/94f6857692b302473250

More mesa-clBLAS issues.  Started fishing on the #dri-devel channel.  Could you guys start testing on mesa?

**Comment by pavanky** [comment]
It is very likely a mesa bug rather than a clBLAS bug. We (arrayfire) important clBLAS functionality on intel, AMD, nvidia, apple, pocl and beignet. They pass our tests without a hitch.

**Comment by anadon** [comment]
Ok.  I'll talk more to the mesa dev's.  But adding mesa as a build target would be nice.

**Comment by pavanky** [comment]
I want to test arrayfire with mesa, but [this bug](https://bugs.freedesktop.org/show_bug.cgi?id=91556) is holding us back.

**Comment by anadon** [comment]
I wonder if what I'm seeing is related or different.  I also have a bug where OpenCL is only detecting 1GB of my card's memory.

**Comment by anadon** [comment]
I'm seeing CAPS_DEBUG and DEBUG_2 as compile time guards for debug code.  What should I be using in src/library/blas/generic/commin2.cc between line 87 and 88 for checking makeKernel error states set by "storeErrorCode()"?

**Comment by anadon** [comment]
Is there a parallel to getErrorString proposed here http://stackoverflow.com/questions/24326432/convenient-way-to-show-opencl-error-codes ?  Grep isn't leading me to anything offhand.
