### ISSUE TITLE
[tests/gtest-external-prefix/src/gtest-external-stamp/gtest-external-download] Error 1

### ISSUE THREAD

**Issue by dendisuhubdy** [clMathLibraries/clBLAS#243]
-- downloading...
     src='https://github.com/google/googletest/archive/release-1.7.0.zip'
     dst='/home/dendisuhubdy/workspace/clBLAS/src/tests/gtest-external-prefix/src/release-1.7.0.zip'
     timeout='none'
CMake Error at gtest-external-stamp/download-gtest-external.cmake:27 (message):
  error: downloading
  'https://github.com/google/googletest/archive/release-1.7.0.zip' failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

**Comment by dendisuhubdy** [comment]
Ok I managed to use a crude way to overcome this error by disabling the MD5 hash check and manually extracting google test release to the parent directory. It worked!

**Comment by anadon** [comment]
It failed the md5 check with the same version?  That sounds more like that github account was compromised and you installed a malicious program, or google violated best practices in their release versioning.  I'll send a message to them asking about it.

**Comment by BillyDonahue** [comment]
Sorry, what md5sum were you expecting?

**Comment by dendisuhubdy** [comment]
In verify-gtest-external.cmake the expected MD5 sum is

expect_value "ef5e700c8a0f3ee123e2e0209b8b4961"

the downloaded file was different. I doubt it's on the Google release part, but as I tried to even download it my libcurl can't allow downloading HTTPS which is weird, because I always use CURL to download files over HTTPS.

**Comment by dendisuhubdy** [comment]
By the way that only happened to me on Ubuntu 14.04 not on Max OS X 10.11

**Comment by dcow** [comment]
Sounds more like you network or machine is compromised if `https` is broken.

**Comment by anadon** [comment]
I have it tested working on my linux system.  dendisuhubdy, I think this is your end and this should be closed.

**Comment by dendisuhubdy** [comment]
agreed. Thanks!

**Comment by anadon** [comment]
You need to be the one to hit the "comment and close" button -- we can't >_<

**Comment by kknox** [comment]
Getting to this late; make sure that your cmake version is at least 2.8.12
