### ISSUE TITLE
How to cite clBLAS?

### ISSUE THREAD

**Issue by hughperkins** [clMathLibraries/clBLAS#266]

**Comment by tingxingdong** [comment]
Like cuda users citing cuBLAS often refer to url on nvidia.com. Since AMD's computing hub is gpuopen.com, you may refer to "http://gpuopen.com/compute-product/clblas/"

**Comment by hughperkins** [comment]
Thanks.  Thoughts on how I would write this in bibtex format?

**Comment by kknox** [comment]
[stackexchange](http://tex.stackexchange.com/questions/3587/how-can-i-use-bibtex-to-cite-a-web-page)

**Comment by hughperkins** [comment]
ok, thanks :-)

**Comment by hughperkins** [comment]
You dont want anything in `author` field?   Currently I'm putting:
```
@misc{clblas,
  title={clBLAS},
  howpublished = {\url{https://github.com/clMathLibraries/clBLAS}},
  note = {Accessed: 2016-05-14}
}
```
