### ISSUE TITLE
event (firstDotCall) leak at xdot.c

### ISSUE THREAD

**Issue by ache7** [clMathLibraries/clBLAS#296]
Cause "out of memory" errors with intel opencl drivers.
Here's the forum thread:
https://software.intel.com/en-us/forums/opencl/topic/701907
And bugfix:
https://github.com/ache7/clBLAS/commit/959372fb480225e6ca7c5f2812c5ab3b524650ef

**Comment by kknox** [comment]
Hi @ache7 
Can you make a PR targeting our /develop branch?  I'll merge this.

**Comment by ache7** [comment]
Here https://github.com/clMathLibraries/clBLAS/pull/297

**Comment by ache7** [comment]
Maybe it's better to initialize firstDotCall to NULL and release firstDotCall event before freeSolutionSeq(&seq). Differs if first makeSolutionSeq or executeSolutionSeq failed.

**Comment by ache7** [comment]
Also, when I search for "eventWaitList, &first" in sources - there is more functions with unreleased events, all these events come to "step->event = events + j;" in makeSolutionSeq, so can be freed automatically somewhere in freeSolutionSeq -> freeSolutionStep -> releaseStepImgs, but I don't see clReleaseEvent() calls. Someone must check this, I don't know code well enough.

**Comment by kknox** [comment]
Hi @ache7 
I have made a [new branch](https://github.com/kknox/clBLAS/tree/fix-event-leak) in my fork that fixes the many events you mention in this thread.  It passes my unit tests.

If you have time, would you mind testing in your environment?  If not, I'll merge my branch as it's already passing my tests.

**Comment by ache7** [comment]
Sorry, I don't use library directly, only through other libraries (from cltorch), so can't test it thoroughly. Seems that neural nets use only xdot() from functions with event leaks.

**Comment by kknox** [comment]
Thanks for replying; I'll close your PR and merge in my fixes.  I think it should square you away.
