### ISSUE TITLE
Tuning

### ISSUE THREAD

**Issue by mikyoreyes** [clMathLibraries/clBLAS#306]
Hi.

Does anyone know how to use the produced .kdb file after tuning?

Thanks,

**Comment by tingxingdong** [comment]
Have you

**Comment by mikyoreyes** [comment]
so with the BLAS_DUMP_CLBLAS_KERNELS turned ON the kernels are created on runtime? 

I'm using an adreno GPU on mobile.

**Comment by tingxingdong** [comment]
Can you just simply run it?

**Comment by ysh329** [comment]
> so with the BLAS_DUMP_CLBLAS_KERNELS turned ON the kernels are created on runtime?
> 
> I'm using an adreno GPU on mobile.

Hi, how about the performance on adreno gpu? thanks in advance
