### ISSUE TITLE
Use the master branch instead of develop

### ISSUE THREAD

**Issue by cirosantilli** [clMathLibraries/clBLAS#314]
It is the dominating git convention by far.

In particular, it makes the repository look inactive on GitHub.

**Comment by pavanky** [comment]
@tingxingdong may be set the default branch to develop instead of master ? This will also help ensure all pull requests are targeted to develop by default instead of master.

**Comment by tingxingdong** [comment]
I agree.

**Comment by tingxingdong** [comment]
but i have not rights.

**Comment by pavanky** [comment]
@kknox thoughts ?
