### ISSUE TITLE
Not able to Build clBLAS from Sources

### ISSUE THREAD

**Issue by saviogeorge** [clMathLibraries/clBLAS#315]
I tried to build the clBLAS on a Centos 7.3 installed PC.
But I get the following error please find the attached Screen shot.

The Computer is not connected to the Network.

![screenshot from 2017-03-29 13-53-15](https://cloud.githubusercontent.com/assets/20711873/24455159/d6ab69e2-148e-11e7-9178-0cd0327a8f8d.png)

**Comment by tingxingdong** [comment]
read this blog.  https://github.com/clMathLibraries/clBLAS/wiki/Build-client,-samples,-gtest

**Comment by saviogeorge** [comment]
Thank you tingxingong for your comment.

So I understand the Problem is due to the following additional dependencies missing on my Computer
•Boost
•GoogleTest
•CPU BLAS ACML or [CBLAS] (http://www.netlib.org/blas/)

Am I right?

**Comment by tingxingdong** [comment]
No,  your problem is only network. 
My suggestion is if you do not need this google test feature, you may turn it off on your cmake-gui.

**Comment by saviogeorge** [comment]
Oh alright!
Thanks a lot for the Information
I will try that
