### ISSUE TITLE
How can I build libclBLAS.so for OSX?

### ISSUE THREAD

**Issue by KCErb** [clMathLibraries/clBLAS#57]
Hi again,

I'm new to the world of `cmake` and `build`ing source code so I'm looking for some help with basic information. If you'd prefer to refer me to materials that I should read I'd be happy to do so :)

Ultimately my goal is to write a Ruby FFI into clBLAS and to get started I just need a `libclBLAS.so` file (like the ones that are available for Linux and Windows on the releases page).

It seems at the moment that I'll need to make it myself and I'm not sure I'm even starting at the right place. I pointed `cmake` at the `src/`directory and, as described in the wiki, it generated a bunch of cmake files. But that's as far as I'm getting :blush: 

Reading through the [wiki page](https://github.com/clMathLibraries/clBLAS/wiki/Build) on this, it seems that I need to install a few dependencies before I can move on. Mostly they are for testing and unfortunately some of them (for example the AMD APP SDK) only have Windows/Linux releases.

How can I go about getting ahold of a clBLAS binary for Mac for use with [Ruby's FFI library](https://github.com/ffi/ffi)?

**Comment by abergeron** [comment]
Just run `make`  in the directory you ran `cmake` in.

**Comment by KCErb** [comment]
Oh wow, thanks lots @abergeron! :heart: 

Should I put up a PR with the build so that you guys can put these right alongside the Windows and Linux ones or are there deeper reasons that OSX users need to build there own?

**Comment by kknox** [comment]
HI @KCErb 
We are not in a position to say that we can support OSX releases at this time.  However, I am pleased that users can download the code on their own and build it.
