### ISSUE TITLE
lience issue

### ISSUE THREAD

**Issue by AndreasMadsen** [clMathLibraries/clBLAS#94]
I was trying to find out who owned this repo, looked in the license and found:

```
Copyright [yyyy] [name of copyright owner]
```

you should fill in the blanks :)

**Comment by TimmyLiu** [comment]
Hi,

This is pretty silly. "Copyright [yyyy] [name of copyright owner]" is actually part of instruction for how to apply license as appendix. I have made pull request #106 to delete it.

The beginning of any file should have the license statement for the information you are looking for.
